language: python
python:
  - "3.7-dev"

cache: pip

install:
  - pip install -r requirements.txt

script:
  - pycodestyle .
  - python manage.py makemigrations && python manage.py migrate && python manage.py test
