language: python
python:
  - "3.7-dev"

cache: pip

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run web sh -c "pycodestyle ."
  - docker-compose run web sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py test"
