version: "3.7"

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:alpine
  web:
    build:
      context: .
      cache_from:
        - "caoliu98/facial-attendance-backend:${TAG}"
    image: "caoliu98/facial-attendance-backend:${TAG}"
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: backend
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A facial_attendance worker -l info
    volumes:
      - .:/backend
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A facial_attendance beat -l info
    volumes:
      - .:/backend
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
